name: Cloudsmith Quota Check

on:
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch:

jobs:
  quota-check:
    runs-on: ubuntu-latest
    environment: Cloudsmith
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          cloudsmith-quota.sh
    - name: Run Script
      run: |
        /bin/bash cloudsmith-quota.sh
      env:
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        CLOUDSMITH_OWNER: ${{ secrets.CLOUDSMITH_OWNER }}
        CLOUDSMITH_REPO: ${{ secrets.CLOUDSMITH_REPO }}
